[build]
  command = "npm run build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "22"
[context.deploy-preview.environment]
  SITE_MODE = "preview"
[context.branch-deploy.environment]
  SITE_MODE = "preview"

[context.production.environment]
  SITE_MODE = "production"
  SITE_URL = "https://camarasyalarmasrapid.com"
