import fs from 'node:fs';
import assert from 'node:assert/strict';
import {e} from '../src/lib.mjs';
const pages=JSON.parse(fs.readFileSync('.cache/pages.json','utf8')),report=JSON.parse(fs.readFileSync('.cache/build-report.json','utf8'));
const byUrl=new Map(pages.map(p=>[p.url,p])),titles=new Set(),descriptions=new Set(),content=new Map(),anchors=new Map();let links=0;
for(const p of pages){const html=fs.readFileSync('dist/'+p.file,'utf8');content.set(p.url,html);assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,'Un H1: '+p.url);assert.ok(html.startsWith('<!doctype html>'));assert.ok(!/undefined|\[object Object\]/.test(html),'Texto incorrecto: '+p.url);assert.ok(!titles.has(p.title),'Título duplicado: '+p.title);titles.add(p.title);assert.ok(!descriptions.has(p.description),'Descripción duplicada: '+p.url);descriptions.add(p.description);assert.ok(html.includes('name="robots" content="'+(p.indexed?'index,follow':'noindex,follow')),'Robots: '+p.url);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'ID duplicado: '+p.url);anchors.set(p.url,new Set(ids));for(const m of html.matchAll(/<img\b([^>]+)>/g)){assert.ok(/\balt="[^"]+"/.test(m[1]),'Alt: '+p.url);assert.ok(/\bwidth=/.test(m[1])&&/\bheight=/.test(m[1]),'Dimensiones: '+p.url);}if(p.townId)for(const phrase of ['Instalación de alarmas en ','Instalación de cámaras en ','Instalación de cámaras y alarmas en '])assert.ok(html.includes(phrase+e(p.town)),phrase+p.town);}
for(const p of pages){const html=content.get(p.url);for(const m of html.matchAll(/\b(?:href|src)="([^"]+)"/g)){const raw=m[1].replaceAll('&amp;','&');if(!raw.startsWith('/')&&!raw.startsWith('#'))continue;links++;const u=new URL(raw,'https://audit.invalid'+p.url);const target=byUrl.get(u.pathname);if(target){if(u.hash)assert.ok(anchors.get(u.pathname).has(decodeURIComponent(u.hash.slice(1))),'Ancla rota: '+raw+' desde '+p.url);}else assert.ok(fs.existsSync('dist'+u.pathname),'Enlace roto: '+raw+' desde '+p.url);}}
assert.equal(pages.filter(p=>p.townId).length,report.municipalities);assert.equal(report.provinces.length,19);assert.equal(report.provinces.reduce((sum,p)=>sum+p.count,0),report.municipalities);assert.ok(fs.existsSync('dist/404.html'));assert.ok(!fs.readFileSync('dist/_redirects','utf8').includes('/* /index.html 200'));
if(report.mode==='preview'){assert.equal(report.indexable,0);assert.ok(!fs.existsSync('dist/sitemap.xml'));assert.match(fs.readFileSync('dist/_headers','utf8'),/X-Robots-Tag: noindex/);}else{assert.ok(fs.existsSync('dist/sitemap.xml'));for(const file of report.sitemaps){const xml=fs.readFileSync('dist'+file,'utf8');for(const m of xml.matchAll(/<loc>([^<]+)<\/loc>/g)){const u=new URL(m[1]);assert.ok(byUrl.get(u.pathname)?.indexed,'Sitemap no indexable: '+m[1]);}}}
const audit={pages:pages.length,localPages:report.municipalities,internalLinks:links,brokenLinks:0,duplicateTitles:0,duplicateDescriptions:0};fs.writeFileSync('.cache/audit-report.json',JSON.stringify(audit,null,2));console.log(`AUDIT OK: ${pages.length} páginas y ${links} enlaces internos; sin enlaces rotos.`);
