import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {provinces,services,brands} from '../src/content.mjs';
import {townsFrom,runtime,approvedLocal,e} from '../src/lib.mjs';
import * as view from '../src/views.mjs';
import {guides,guidesPage,guidePage,guideUrl} from '../src/guides.mjs';
import {facilities,facilitiesPage,facilityPage,facilityUrl,validateFacilities} from '../src/facilities.mjs';
import {enrichMetadata} from '../src/metadata.mjs';
import {localSeoMeta} from '../src/local-variants.mjs';
const started=performance.now(),read=file=>JSON.parse(fs.readFileSync(file,'utf8'));
const site=read('config/site.json'),locals=read('config/local-content.json'),rt=runtime(site);
const source=read('data/municipios.json'),towns=townsFrom(source.municipalities),ids=new Set(towns.map(t=>t.id));
site.directoryCount=towns.length;
validateFacilities(towns);
for(const [id,entry] of Object.entries(locals.approved)){if(!ids.has(id))throw Error('Municipio desconocido: '+id);if(!approvedLocal(entry))throw Error('Contenido local sin revisión completa: '+id);}
for(const media of read('data/media-sources.json')){const file='public/assets/'+media.file;if(!fs.existsSync(file))throw Error('Falta imagen: '+file);const actual=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');if(media.sha256&&actual!==media.sha256)throw Error('Imagen distinta a su fuente: '+file);}
const out=path.resolve('dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.mkdirSync('.cache',{recursive:true});
fs.cpSync('public/assets',path.join(out,'assets'),{recursive:true});
const assets={};for(const [key,file,ext] of [['css','public/styles.css','css'],['js','public/app.js','js']]){const data=key==='css'?Buffer.concat([fs.readFileSync(file),Buffer.from('\n'),fs.readFileSync('public/enhancements.css'),Buffer.from('\n'),fs.readFileSync('public/ajax-accent.css'),Buffer.from('\n'),fs.readFileSync('public/editorial.css'),Buffer.from('\n'),fs.readFileSync('public/privacy-camera.css'),Buffer.from('\n'),fs.readFileSync('public/facilities.css'),Buffer.from('\n'),fs.readFileSync('public/quote-form.css'),Buffer.from('\n'),fs.readFileSync('public/multibrand.css'),Buffer.from('\n'),fs.readFileSync('public/local-variants.css'),Buffer.from('\n'),fs.readFileSync('public/local-intent.css'),Buffer.from('\n'),fs.readFileSync('public/final-ui.css')]):Buffer.concat([fs.readFileSync(file),Buffer.from('\n'),fs.readFileSync('public/cookies.js'),Buffer.from('\n'),fs.readFileSync('public/quote-form.js')]),hash=crypto.createHash('sha256').update(data).digest('hex').slice(0,12);assets[key]=`/assets/${key}.${hash}.${ext}`;fs.writeFileSync(out+assets[key],data);}
fs.writeFileSync(out+'/assets/municipios-search.json',JSON.stringify(towns.map(t=>({name:t.name,province:t.province.name,url:t.url}))));
const pages=[],urls=new Set();
const add=original=>{const page=enrichMetadata(original);if(urls.has(page.url))throw Error('URL duplicada: '+page.url);urls.add(page.url);const relative=page.url==='/404.html'?'404.html':page.url.slice(1)+'index.html',file=path.join(out,relative);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,view.shell(page,site,rt,assets));const {body,...metadata}=page;pages.push({...metadata,file:relative,indexed:rt.production&&page.indexable!==false});};
const crumbs=(...entries)=>entries.map(([name,url])=>({name,url}));
add({url:'/',title:'Instalación de alarmas y cámaras de seguridad',description:'Alarmas inalámbricas de grado 2, cámaras con visión nocturna e instalación profesional. Sin cuota mensual obligatoria. Consulta tu pueblo: '+site.phone+'.',body:view.home(towns)});
add({url:'/guias/',title:'Guías de alarmas y cámaras de seguridad',description:'Guías para elegir alarmas sin cuotas, visión nocturna, seguridad en segundas residencias y presupuestos de instalación.',body:guidesPage(),crumbs:crumbs(['Guías','/guias/'])});
for(const g of guides)add({url:guideUrl(g),title:g.title,description:g.description,body:guidePage(g),guide:true,image:g.category==='CÁMARAS'?'ajax-turret.jpg':'ajax-kit.jpg',crumbs:crumbs(['Guías','/guias/'],[g.label,guideUrl(g)])});
add({url:'/soluciones/',title:'Soluciones de seguridad según el tipo de inmueble',description:'Alarmas y cámaras para viviendas, casas, comercios, oficinas y almacenes. Define accesos, vídeo y usuarios antes de elegir equipos.',body:facilitiesPage(),crumbs:crumbs(['Soluciones','/soluciones/'])});
for(const f of facilities)add({url:facilityUrl(f),title:f.title,description:f.description,body:facilityPage(f),image:f.image,facility:f.slug,crumbs:crumbs(['Soluciones','/soluciones/'],[f.label,facilityUrl(f)])});
for(const s of services)add({url:`/${s.slug}/`,title:s.title,description:s.intro,body:view.servicePage(s),crumbs:crumbs([s.name,`/${s.slug}/`])});
add({url:'/marcas/',title:'Marcas de alarmas y videovigilancia',description:'Instalaciones con Ajax, Hikvision, Dahua, Uniview, Nivian y EZVIZ. Selección de equipos e integración según las necesidades de tu inmueble.',body:view.brandsPage(),crumbs:crumbs(['Marcas','/marcas/'])});
for(const b of brands)add({url:`/marcas/${b.slug}/`,title:'Instalación de '+(b.slug==='ajax'?'sistemas ':'cámaras ')+b.name,description:b.text,body:view.brandPage(b),crumbs:crumbs(['Marcas','/marcas/'],[b.name,`/marcas/${b.slug}/`])});
add({url:'/zonas/',title:'Instalación de alarmas y cámaras por pueblos',description:'Encuentra tu municipio y consulta la instalación de alarmas, cámaras de seguridad y sistemas integrados. Directorio de provincias y localidades.',body:view.zonesPage(towns),crumbs:crumbs(['Zonas','/zonas/'])});
for(const p of provinces){const group=towns.filter(t=>t.province.id===p.id);if(!group.length)throw Error('Provincia sin municipios: '+p.name);const approvedInProvince=group.filter(t=>approvedLocal(locals.approved[t.id])).length;add({url:p.url,title:'Alarmas y cámaras de seguridad en '+p.name,description:`Instalación de alarmas y cámaras en los municipios de ${p.name}. Soluciones inalámbricas, visión nocturna e integración según equipo. ${site.phone}.`,body:view.provincePage(p,group),province:p.slug,indexable:true,approvedInProvince,crumbs:crumbs(['Zonas','/zonas/'],[p.name,p.url])});
 for(let i=0;i<group.length;i++){const t=group[i],entry=locals.approved[t.id],peers=group.slice(Math.max(0,i-3),i+4).filter(x=>x.id!==t.id),seo=localSeoMeta(t,site.phone);add({url:t.url,title:seo.title,description:seo.description,body:view.townPage(t,peers,entry),indexable:true,town:t.name,townId:t.id,province:p.slug,provinceName:p.name,crumbs:crumbs(['Zonas','/zonas/'],[p.name,p.url],[t.name,t.url])});}
}
add({url:'/contacto/',title:'Presupuesto de instalación de alarmas y cámaras',description:'Consulta una instalación de alarma, cámaras o ambos sistemas. Contacto directo por teléfono y WhatsApp: '+site.phone+'.',body:view.contactPage(site),crumbs:crumbs(['Contacto','/contacto/'])});
for(const [slug,title] of [['aviso-legal','Aviso legal'],['privacidad','Privacidad'],['cookies','Cookies y servicios externos']])add({url:`/${slug}/`,title,description:title+' de Cámaras y Alarmas Rapid. Información sobre el sitio y sus servicios.',body:view.legalPage(slug,site,rt),indexable:false,crumbs:crumbs([title,`/${slug}/`])});
add({url:'/404.html',title:'Página no encontrada',description:'La página solicitada no existe. Consulta las soluciones de seguridad o busca tu municipio en el directorio de Cámaras y Alarmas Rapid.',indexable:false,body:'<section class="not-found wrap"><p class="eyebrow">404 · PÁGINA NO ENCONTRADA</p><h1>Volvamos a un<br>lugar seguro.</h1><p>Esta dirección no existe. Puedes ir a la portada o buscar tu municipio.</p><a class="button" href="/">Volver al inicio</a> <a class="text-link" href="/zonas/">Ver zonas de instalación</a></section>'});
const indexed=pages.filter(p=>p.indexed),sitemaps=[];
if(rt.production){fs.mkdirSync(out+'/sitemaps',{recursive:true});const writeMap=(name,entries)=>{if(!entries.length)return;const loc='/sitemaps/'+name+'.xml';fs.writeFileSync(out+loc,'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+entries.map(p=>`<url><loc>${e(rt.base+p.url)}</loc></url>`).join('')+'</urlset>');sitemaps.push(loc);};writeMap('principal',indexed.filter(p=>!p.townId));for(const p of provinces)writeMap(p.slug,indexed.filter(x=>x.townId&&x.province===p.slug));fs.writeFileSync(out+'/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+sitemaps.map(url=>`<sitemap><loc>${e(rt.base+url)}</loc></sitemap>`).join('')+'</sitemapindex>');}
fs.writeFileSync(out+'/robots.txt','User-agent: *\nAllow: /\n'+(rt.production?'Sitemap: '+rt.base+'/sitemap.xml\n':''));
fs.writeFileSync(out+'/_redirects','https://www.alarmasycamarasrapid.com/* https://alarmasycamarasrapid.com/:splat 301!\nhttp://www.alarmasycamarasrapid.com/* https://alarmasycamarasrapid.com/:splat 301!\nhttp://alarmasycamarasrapid.com/* https://alarmasycamarasrapid.com/:splat 301!\n/index.html / 301!\n/:section/index.html /:section/ 301!\n/:province/:town/index.html /:province/:town/ 301!\n/guipuzcoa /gipuzkoa/ 301!\n/guipuzcoa/* /gipuzkoa/:splat 301!\n/vizcaya /bizkaia/ 301!\n/vizcaya/* /bizkaia/:splat 301!\n');
const csp="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'";
fs.writeFileSync(out+'/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: ${csp}\n${rt.production?'':'  X-Robots-Tag: noindex, follow\n'}/assets/*\n  Cache-Control: public, max-age=86400\n`);
const report={mode:rt.production?'production':'preview',domain:rt.base||null,pages:pages.length,municipalities:towns.length,provinces:provinces.map(p=>({name:p.name,slug:p.slug,count:towns.filter(t=>t.province.id===p.id).length})),indexable:indexed.length,approvedLocalities:Object.keys(locals.approved).length,indexStrategy:'Core pages + 19 province pages + all 3797 municipality pages',sitemaps,seconds:Math.round((performance.now()-started)/10)/100};
fs.writeFileSync('.cache/pages.json',JSON.stringify(pages));fs.writeFileSync('.cache/build-report.json',JSON.stringify(report,null,2));
console.log(`BUILD OK: ${pages.length} páginas, ${towns.length} municipios, ${provinces.length} provincias; modo ${report.mode}.`);
