from pathlib import Path
root=Path('.')
def edit(file,old,new,count=1):
 p=root/file;s=p.read_text();assert s.count(old)==count,(file,old[:80],s.count(old));p.write_text(s.replace(old,new))
edit('src/views.mjs',"import {cookieUI}","import {facilitySection,municipalContext} from './facilities.mjs';\nimport {cookieUI}")
edit('src/views.mjs','${homeKnowledge()}','${facilitySection()}${homeKnowledge()}')
edit('src/views.mjs',"${localEcosystem()}${localUsageGuide()}","${municipalContext(t)}${facilitySection(t)}${localEcosystem()}${localUsageGuide()}")
edit('src/views.mjs',"${serviceKnowledge(s.slug)}", "<div class=\"wrap\"><a class=\"text-link\" href=\"/soluciones/\">Elegir solución según mi inmueble →</a></div>${serviceKnowledge(s.slug)}")
edit('src/views.mjs',"${link('/zonas/','Cambiar provincia')}","${link('/zonas/','Cambiar provincia')}${link('/soluciones/','Soluciones por inmueble')}")
edit('src/views.mjs','<a href="/zonas/">Provincias y pueblos</a>','<a href="/zonas/">Provincias y pueblos</a><a href="/soluciones/">Soluciones por inmueble</a>')
edit('src/views.mjs','<option>Vivienda</option><option>Negocio</option><option>Segunda residencia</option><option>Otro</option>','<option>Vivienda</option><option>Casa o chalet</option><option>Segunda residencia</option><option>Comercio o local</option><option>Oficina</option><option>Nave o almacén</option><option>Negocio</option><option>Otro</option>')
edit('public/app.js',"if(town)form.elements.town.value=town.slice(0,100);form.addEventListener", "if(town)form.elements.town.value=town.slice(0,100);const building=params.get('inmueble');if(building&&Array.from(form.elements.building.options).some(option=>option.value===building))form.elements.building.value=building;form.addEventListener")
edit('scripts/build.mjs',"import {enrichMetadata}","import {facilities,facilitiesPage,facilityPage,facilityUrl,validateFacilities} from '../src/facilities.mjs';\nimport {enrichMetadata}")
edit('scripts/build.mjs','site.directoryCount=towns.length;','site.directoryCount=towns.length;\nvalidateFacilities(towns);')
edit('scripts/build.mjs',"fs.readFileSync('public/privacy-camera.css')", "fs.readFileSync('public/privacy-camera.css'),Buffer.from('\\n'),fs.readFileSync('public/facilities.css')")
edit('scripts/build.mjs',"for(const s of services)add", "add({url:'/soluciones/',title:'Soluciones de seguridad según el tipo de inmueble',description:'Alarmas y cámaras para viviendas, casas, comercios, oficinas y almacenes. Define accesos, vídeo y usuarios antes de elegir equipos.',body:facilitiesPage(),crumbs:crumbs(['Soluciones','/soluciones/'])});\nfor(const f of facilities)add({url:facilityUrl(f),title:f.title,description:f.description,body:facilityPage(f),image:f.image,facility:f.slug,crumbs:crumbs(['Soluciones','/soluciones/'],[f.label,facilityUrl(f)])});\nfor(const s of services)add")
edit('tests/site.test.mjs',"import test from 'node:test';", "import './facilities.test.mjs';\nimport test from 'node:test';")
edit('scripts/content-audit.mjs',"import fs from 'node:fs';", "import {facilities,localContexts} from '../src/facilities.mjs';\nimport fs from 'node:fs';")
edit('scripts/content-audit.mjs',"guides:pages.filter(p=>p.guide).length,", "guides:pages.filter(p=>p.guide).length,facilityPages:facilities.length,municipalContexts:Object.keys(localContexts).length,contextScope:'Contexto municipal público; no acredita atención, obras ni aprobación para indexación.',")
print('integrated')
