import {e} from './lib.mjs';

export const ajaxAccessories=[
 ['Puertas y ventanas','DoorProtect','Detecta la apertura de puertas y ventanas. Lo planteamos para vigilar los accesos y saber qué punto ha activado la alarma.','https://support.ajax.systems/es/manuals/doorprotect/'],
 ['Movimiento interior','MotionProtect','Detección de movimiento por infrarrojos pasivos (PIR) para estancias y zonas de paso. Elegimos la ubicación según recorridos, obstáculos y mascotas.','https://ajax.systems/products/motionprotect/'],
 ['Detección tipo cortina','MotionProtect Curtain','Cubre una franja estrecha en accesos interiores. Permite proteger un paso concreto sin tratar toda la estancia como una misma zona; este modelo es para interior.','https://ajax.systems/products/motionprotect-curtain/'],
 ['Fotos de alarma','MotionCam','Combina detección con fotografías asociadas a una alarma. Ayuda a comprobar qué ha ocurrido sin confundir fotoverificación con grabación de vídeo continua.','https://ajax.systems/es/support/manuals/motioncam/'],
 ['Aviso sonoro','HomeSiren y StreetSiren','Sirenas inalámbricas para avisar en el interior o exterior con el modelo correspondiente. Configuramos su respuesta a los eventos previstos en el proyecto.','https://ajax.systems/products/streetsiren/'],
 ['Fugas de agua','LeaksProtect','Detecta la presencia de agua en puntos de riesgo, como bajo un fregadero o junto a una lavadora. El detector avisa; cerrar el agua requiere una solución de corte compatible adicional.','https://ajax.systems/products/leaksprotect/'],
 ['Humo e incendio','Gama FireProtect','Opciones para detectar humo y otras señales de incendio según la versión elegida. Especificamos los sensores del modelo: no todos incluyen las mismas funciones ni detección de monóxido.','https://ajax.systems/'],
 ['Control del sistema','Teclados y mandos Ajax','Opciones para armar, desarmar y gestionar el acceso de las personas autorizadas. Elegimos controles y permisos acordes al uso de la vivienda o negocio.','https://ajax.systems/tools/devices-compatibility/']
];

export function ajaxRange(){
 return `<section class="section wrap service-knowledge ajax-range" id="ecosistema-ajax" aria-labelledby="ajax-range-title"><div class="section-heading"><div><p class="eyebrow">JEWELLER · TECNOLOGÍA INALÁMBRICA AJAX</p><h2 id="ajax-range-title">Seguridad profesional.<br><span class="muted">Sin cables entre detectores.</span></h2></div><p>Jeweller es la tecnología de radio propia de Ajax para conectar la central con los dispositivos compatibles. Comunicación bidireccional, cifrado y autenticación de dispositivos para proteger el intercambio de información.</p></div><div class="practical-grid"><article><h3>Comunicación protegida.</h3><p>El cifrado y la autenticación forman parte del enlace Jeweller. La seguridad no depende solo de una contraseña de usuario: también importa cómo se comunican los equipos.</p></article><article><h3>Estado supervisado.</h3><p>El sistema comprueba la comunicación con sus dispositivos. Revisamos señal, ubicaciones y configuración para detectar pérdidas de enlace y obtener una conexión estable.</p></article><article><h3>Diseñada para crecer.</h3><p>Podemos estudiar nuevos detectores y accesorios sin tender un cable desde cada uno hasta la central. La ampliación depende de la capacidad y compatibilidad del hub instalado.</p></article></div><p class="source-links"><a href="https://ajax.systems/support/posts/jeweller-radio-protocol/" target="_blank" rel="noopener noreferrer">Conocer la tecnología Jeweller en Ajax ↗</a> · <a href="https://ajax.systems/tools/devices-compatibility/" target="_blank" rel="noopener noreferrer">Consultar compatibilidad de dispositivos ↗</a></p><div class="section-heading"><div><p class="eyebrow">BASELINE Y EL ECOSISTEMA AJAX</p><h2>Mucho más que<br><span class="muted">detectar una intrusión.</span></h2></div><p>Protección de accesos y movimiento, aviso sonoro y opciones de detección de humo o inundación. Cada dispositivo tiene una función concreta.</p></div><div class="practical-grid">${ajaxAccessories.map(([title,model,text,url])=>`<article><p class="eyebrow">${e(model)}</p><h3>${e(title)}</h3><p>${e(text)}</p><p class="source-links"><a href="${url}" target="_blank" rel="noopener noreferrer">Información de Ajax ↗</a></p></article>`).join('')}</div><p class="knowledge-note">Los dispositivos de intrusión, incendio y automatización pertenecen a distintas categorías del ecosistema. Confirmamos compatibilidad, alimentación y configuración antes de instalar. Ninguna tecnología inalámbrica es invulnerable a las interferencias; el grado de seguridad corresponde a los equipos y al diseño de la instalación.</p><p class="source-links"><a href="/contacto/">Pedir una propuesta de alarma y accesorios →</a></p></section>`;
}
