import {e} from './lib.mjs';
// Original editorial guidance. Capabilities below apply to named ranges/models only.
export const cameraBrands={
 hikvision:{
  description:'Instalación de cámaras Hikvision: ColorVu, AcuSense, grabación y acceso móvil. Selección de equipos según luz, accesos y necesidades de tu inmueble.',
  intro:'Una entrada con poca luz y un patio con movimiento no necesitan exactamente lo mismo. En Hikvision distinguimos calidad de imagen, clasificación de eventos y almacenamiento antes de elegir el equipo.',
  cards:[
   ['IMAGEN NOCTURNA','ColorVu: conservar el color.','ColorVu está orientada a obtener imágenes en color con poca luz. En escenarios muy oscuros puede intervenir la iluminación auxiliar del equipo. Al elegir la cámara revisamos la luz disponible, la distancia al acceso y si un foco visible encaja en ese lugar.'],
   ['AVISOS RELEVANTES','AcuSense: personas y vehículos.','Las soluciones AcuSense permiten clasificar personas y vehículos para filtrar eventos de movimiento. No prometen eliminar todos los avisos incorrectos. El encuadre, las reglas y los horarios se ajustan al uso del inmueble, y comprobamos qué funciones aporta la cámara o el grabador elegido.'],
   ['TU INSTALACIÓN','No todo se resuelve con más resolución.','Para ver una puerta necesitamos definir qué detalle quieres reconocer y a qué distancia. En una propuesta con varias cámaras concretamos óptica, conexión, grabador y disco. Una imagen nítida en directo no confirma por sí sola que exista un archivo recuperable.']
  ],
  example:['Una entrada y un patio, dos decisiones.','Como propuesta de diseño, podemos priorizar el encuadre de la puerta y estudiar detección de personas en el patio. Antes de presupuestar pedimos una descripción de accesos, puntos de corriente y conexión. Después comprobamos una escena nocturna y una reproducción del archivo. Es un ejemplo de solución, no una instalación realizada ni un kit cerrado.'],
  faq:[['¿ColorVu y AcuSense son lo mismo?','No. ColorVu se centra en la imagen en color con poca luz; AcuSense, en la clasificación de objetivos para determinados eventos. La combinación disponible depende de la referencia.'],['¿Se pueden aprovechar cámaras que ya tengo?','Revisamos el modelo, cableado, alimentación y grabador. Conservar equipos puede ser una opción, pero su compatibilidad y las funciones disponibles deben comprobarse antes.']],
  sources:[['AcuSense','https://content.hikvision.com/es/tecnologia/acusense'],['ColorVu','https://content.hikvision.com/es/tecnologia/colorvu2020']]
 },
 dahua:{
  description:'Instalación de cámaras Dahua: WizSense, iluminación Smart Dual Light y grabación. Proyectos de videovigilancia para viviendas, comercios y accesos.',
  intro:'Para elegir una solución Dahua separamos tres cuestiones: qué evento te interesa detectar, cómo se ilumina por la noche y dónde necesitas conservar las imágenes.',
  cards:[
   ['DETECCIÓN','WizSense: centrar los avisos.','WizSense reúne equipos con funciones de análisis de personas y vehículos. En las referencias compatibles ayuda a filtrar avisos que no corresponden al objetivo configurado. Elegimos reglas de detección y zonas con criterio; no basta con activar todas las opciones del menú.'],
   ['LUZ NOCTURNA','Smart Dual Light: luz cuando hace falta.','La tecnología Smart Dual Light combina infrarrojos e iluminación cálida. En su modo inteligente puede pasar de imagen infrarroja a color al detectar un objetivo compatible y regresar después. Revisamos la referencia y el escenario: la luz visible puede afectar a vecinos o a zonas de paso.'],
   ['ARCHIVO','Grabar y poder encontrar el evento.','Al definir el sistema concretamos el modo de grabación, el disco o tarjeta y la forma de revisar las imágenes. La capacidad se calcula según cámaras, calidad y actividad. En la entrega comprobamos el archivo y los permisos, además de la imagen que ves en el móvil.']
  ],
  example:['Vigilar un acceso sin iluminarlo siempre.','Una posible solución para un acceso privado es estudiar iluminación inteligente y reglas que prioricen personas. El encuadre no debe depender solo del soporte disponible: importa dónde estará el sujeto y qué se necesita ver. Si ya existe un grabador, comprobamos sus prestaciones antes de proponer una sustitución o ampliación. El proyecto final se define tras revisar el inmueble.'],
  faq:[['¿Todas las cámaras Dahua tienen luz y sirena?','No. Iluminación dual, audio, sirena y analítica varían entre referencias. El presupuesto debe identificar las funciones del modelo, no atribuirlas a toda la marca.'],['¿Una alerta de cámara sustituye a una alarma?','No son equivalentes. El vídeo ayuda a observar y comprobar eventos; para detección de intrusión estudiamos también los accesos, detectores, comunicaciones y uso de la alarma.']],
  sources:[['WizSense','https://www.dahuasecurity.com/es/products/All-Products/Network-Cameras/WizSense-Series/3-Series/WizColor/IPC-HFW3449T1-AS-PV-PRO'],['Smart Dual Light','https://activity.dahuasecurity.com/smart-dual-light/']]
 },
 uniview:{
  description:'Instalación de cámaras Uniview y soluciones ColorHunter. Estudio de iluminación nocturna, encuadre y grabación para viviendas y negocios.',
  intro:'En una instalación Uniview importa tanto la cámara como la escena que debe observar. Elegimos la solución pensando en el acceso, el archivo de vídeo y la forma de consultar los eventos.',
  cards:[
   ['COLOR NOCTURNO','ColorHunter: más información de la escena.','ColorHunter combina óptica, sensor e iluminación de apoyo en las referencias correspondientes para captar detalles en color con poca luz. En oscuridad intensa necesita la iluminación prevista. No equivale a prometer imagen en color sin ninguna luz ni a garantizar identificación a cualquier distancia.'],
   ['EVENTOS','Detección de intrusión según equipo.','La gama ColorHunter incluye referencias que incorporan Smart Intrusion Prevention. La combinación de imagen y análisis depende del modelo. Durante el proyecto definimos qué línea o zona se vigila y cómo interpretar sus avisos, en lugar de presentar cualquier movimiento como una intrusión confirmada.'],
   ['DISEÑO','Una red y un archivo dimensionados.','Para varias cámaras estudiamos los puntos de red, alimentación y el almacenamiento necesario. Detallamos el grabador y la capacidad elegidos. Si se pretende integrar vídeo con otros equipos, comprobamos protocolos y funciones por referencia; compartir marca o resolución no demuestra compatibilidad completa.']
  ],
  example:['Un proyecto pensado para revisar imágenes.','Para una vivienda o pequeño negocio, planteamos qué accesos interesa ver, qué detalle se necesita y quién consultará el archivo. También revisamos la luz disponible durante el cierre. La propuesta puede priorizar una cámara bien situada antes que añadir más unidades sin un objetivo. Comprobamos la búsqueda y reproducción de eventos como parte de la puesta en marcha.'],
  faq:[['¿ColorHunter elimina la necesidad de luz?','No. Su rendimiento en baja iluminación no elimina el papel de la luz auxiliar en escenas muy oscuras. Se elige y configura según el lugar.'],['¿Cuántos días se conservarán las imágenes?','Hay que dimensionar almacenamiento y configuración, y aplicar el plazo que corresponda al uso. No damos una duración fija sin conocer número de cámaras, calidad y modo de grabación.']],
  sources:[['ColorHunter y modelos compatibles','https://www.uniview.com/Technology/ColorHunter/']]
 },
 nivian:{
  description:'Instalación de cámaras Nivian, incluidas soluciones 4G con batería y panel solar. Cobertura, alimentación y grabación estudiadas para cada ubicación.',
  intro:'En una segunda residencia o ubicación sin conexión fija, primero comprobamos cómo llegará Internet y cómo se alimentará la cámara. Una solución 4G puede encajar, pero no evita estudiar cobertura y autonomía.',
  cards:[
   ['SIN CONEXIÓN FIJA','Una opción concreta: NV-CAM01-SOLAR4G.','Este modelo Nivian utiliza conexión 4G, batería y panel solar. Permite consultar imágenes con EseeCloud y almacenar grabaciones en una tarjeta microSD compatible. La SIM y su tarifa de datos se contratan aparte: no deben confundirse con una cuota de central receptora de alarmas.'],
   ['ENERGÍA Y GRABACIÓN','La autonomía depende del uso.','En este modelo existen modos de grabación orientados a ahorrar batería; la grabación continua está condicionada por su nivel. Estudiamos orientación solar, sombras y actividad prevista. No prometemos grabación permanente o autonomía ilimitada solo por añadir un panel solar.'],
   ['PRUEBAS','Cobertura donde va la cámara.','No nos basta con que el teléfono tenga cobertura en la puerta. Antes de fijar el equipo revisamos señal en la ubicación prevista y planteamos cómo acceder al archivo. Si el uso requiere largas consultas en directo, ese consumo debe entrar en la elección de conectividad y alimentación.']
  ],
  example:['Una finca o acceso sin fibra.','Como ejemplo de proyecto, estudiaríamos si hay un punto con cobertura móvil y buena orientación para el panel. También comprobaríamos qué zona es relevante y dónde puede montarse el equipo con acceso para mantenimiento. Cuando existe alimentación y red, valoraríamos igualmente una solución cableada: la opción solar no es automáticamente la mejor para todas las necesidades.'],
  faq:[['¿La cámara 4G funciona sin pagar datos?','Necesita una SIM operativa y un servicio de datos adecuado. El consumo y las condiciones dependen de la tarifa y del uso; se separan del precio de instalación.'],['¿Cualquier cámara Nivian usa la misma aplicación?','No lo damos por supuesto. En el modelo descrito se utiliza EseeCloud. Aplicación, almacenamiento y posibilidades de integración deben comprobarse para la referencia contratada.']],
  sources:[['Ficha de NV-CAM01-SOLAR4G','https://www.nivianhome.com/es/producto/nv-cam01-solar4g/']]
 },
 ezviz:{
  description:'Instalación de cámaras EZVIZ para el hogar. Soluciones como H3c 2K: visión nocturna, consulta móvil y almacenamiento local o nube opcional.',
  intro:'Para vigilar un acceso doméstico conviene decidir primero cómo se conecta la cámara y dónde guardará las imágenes. Con EZVIZ detallamos esas diferencias antes de hablar de funciones de la aplicación.',
  cards:[
   ['UN MODELO DE REFERENCIA','H3c 2K: cámara para exterior.','La H3c 2K combina conexión Wi-Fi, detección de siluetas humanas y opciones de visión nocturna. Cuenta con infrarrojos y focos para obtener imagen en color. Estas funciones pertenecen al modelo descrito; no se atribuyen automáticamente a cualquier cámara de la marca.'],
   ['ALMACENAMIENTO','Tarjeta local o CloudPlay.','Este modelo permite grabar en microSD y contempla CloudPlay como servicio de nube por suscripción donde esté disponible. Diferenciamos la compra de la tarjeta, instalación y cualquier servicio opcional. El acceso a una imagen en directo no demuestra que la grabación esté configurada.'],
   ['CONEXIÓN','Wi-Fi no significa sin alimentación.','La H3c 2K necesita alimentación eléctrica. Revisamos el punto de corriente, cobertura de red y montaje exterior antes de instalarla. Para otros modelos, las opciones de batería o panel solar se comprueban en su ficha; no trasladamos sus prestaciones a esta referencia.']
  ],
  example:['Consultar la entrada desde el móvil.','Una propuesta doméstica puede empezar por una cámara que cubra el acceso importante sin captar más espacio del necesario. Decidimos los avisos útiles, el tipo de almacenamiento y quién tendrá acceso. Tras configurar, comprobamos una grabación y explicamos cómo consultarla. No pedimos que envíes contraseñas o códigos al solicitar información: la cuenta debe mantenerse bajo tu control.'],
  faq:[['¿Es obligatorio pagar CloudPlay?','En la H3c 2K el almacenamiento local mediante microSD es una alternativa; CloudPlay es opcional y requiere suscripción. Confirmamos las opciones de cada referencia.'],['¿Se integrará con una alarma Ajax?','No lo prometemos por el nombre de la marca. Hay que verificar protocolos, equipos y funciones concretas. Puede ser necesario utilizar aplicaciones separadas.']],
  sources:[['Ficha oficial de H3c 2K','https://www.ezviz.com/es/product/H3c-2K/51871']]
 }
};
export function cameraBrandContent(slug){
 const b=cameraBrands[slug];if(!b)return '';
 return `<section class="section wrap camera-brand-content" aria-labelledby="camera-brand-title"><div class="section-heading"><div><p class="eyebrow">TECNOLOGÍA CON UN OBJETIVO</p><h2 id="camera-brand-title">Elegir la cámara.<br><span class="muted">Diseñar la solución.</span></h2></div><p>${e(b.intro)}</p></div><div class="camera-brand-grid">${b.cards.map(([label,title,text])=>`<article><p class="eyebrow">${e(label)}</p><h3>${e(title)}</h3><p>${e(text)}</p></article>`).join('')}</div><aside class="camera-brand-case"><h3>${e(b.example[0])}</h3><p>${e(b.example[1])}</p></aside><div class="camera-brand-faq">${b.faq.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</div><p class="source-links">Referencias técnicas del fabricante: ${b.sources.map(([title,url])=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(title)} ↗</a>`).join(' · ')}. Equipos de referencia; prestaciones y disponibilidad se confirman al presupuestar.</p><p><a class="text-link" href="/contacto/?marca=${slug}">Consultar una instalación de esta marca →</a></p></section>`;
}
export function cameraPlanner(){return `<section class="camera-planner wrap" id="elegir-camaras" aria-labelledby="camera-planner-title"><p class="eyebrow">ANTES DE COMPRAR EQUIPOS</p><h2 id="camera-planner-title">¿Por dónde empezamos?</h2><details><summary>Tengo Internet y quiero vigilar varios accesos.</summary><p>Estudiamos red, alimentación, encuadres y almacenamiento. Compara criterios de imagen y eventos en <a href="/marcas/hikvision/">Hikvision</a>, <a href="/marcas/dahua/">Dahua</a> y <a href="/marcas/uniview/">Uniview</a>, sin elegir solo por los megapíxeles. Para cada cámara conviene definir qué debe verse, no únicamente dónde cabe.</p></details><details><summary>No tengo fibra o necesito valorar una cámara solar.</summary><p>Primero revisamos cobertura móvil y energía. La <a href="/marcas/nivian/">opción Nivian 4G</a> ilustra cómo se relacionan SIM, batería y grabación. Un panel necesita una ubicación adecuada y no convierte el sistema en ilimitado. Consulta también la <a href="/guias/seguridad-segunda-residencia/">guía para segundas residencias</a>.</p></details><details><summary>Busco algo doméstico o ya tengo cámaras.</summary><p>Para una instalación doméstica revisa <a href="/marcas/ezviz/">las opciones EZVIZ de conexión y almacenamiento</a>. Si ya tienes equipos, indícanos las referencias y el grabador sin enviar claves. Comprobamos qué puede conservarse y qué integración es viable. La <a href="/guias/presupuesto-instalacion/">guía de presupuestos</a> ayuda a comparar propuestas con el mismo alcance.</p></details></section>`;}
