export const provinces=[['01','Álava','alava'],['48','Bizkaia','bizkaia'],['20','Gipuzkoa','gipuzkoa'],['09','Burgos','burgos'],['39','Cantabria','cantabria'],['31','Navarra','navarra'],['26','La Rioja','la-rioja'],['24','León','leon'],['47','Valladolid','valladolid'],['49','Zamora','zamora'],['05','Ávila','avila'],['34','Palencia','palencia'],['37','Salamanca','salamanca'],['40','Segovia','segovia'],['42','Soria','soria'],['28','Madrid','madrid'],['33','Asturias','asturias'],['45','Toledo','toledo'],['19','Guadalajara','guadalajara']].map(([id,name,slug])=>({id,name,slug,url:`/${slug}/`}));
export const services=[
 {slug:'alarmas',name:'Alarmas',title:'Instalación de alarmas inalámbricas',headline:'Discretas por fuera. Preparadas por dentro.',image:'ajax-kit.jpg',intro:'Protección para puertas, ventanas y zonas de paso. Diseñamos una alarma Ajax de grado 2 con los equipos y la configuración adecuados para tu vivienda o negocio, sin cuota mensual obligatoria por el sistema autogestionado.',blocks:[
 ['Detectores sin cables. Instalación discreta.','Los detectores compatibles se comunican por radio con la central. No es necesario cablear cada punto de detección. La central sí necesita alimentación y conectividad para enviar avisos; comprobamos cobertura antes de fijar los equipos.'],
 ['Grado 2, con un proyecto bien definido.','Proponemos equipos certificados y una configuración acorde al inmueble. No basta con el nombre de la marca: el grado debe corresponder a los componentes y al diseño de la instalación. Ningún sistema es invulnerable.'],
 ['Sin una cuota obligatoria cada mes.','La propuesta base es autogestionada y no incluye central receptora de alarmas. Instalación, equipos y extras se diferencian en el presupuesto. La SIM de datos, el mantenimiento y otros servicios opcionales pueden tener costes propios.'],
 ['Una alarma adaptada a tu día a día.','Estudiamos los accesos y cómo se utiliza el inmueble para distribuir sensores, sirenas y controles. Te explicamos el armado y la gestión de usuarios. Un detector con fotos sirve para verificar eventos, no sustituye a una cámara de grabación continua.']]},
 {slug:'camaras',name:'Cámaras',title:'Instalación de cámaras de seguridad',headline:'Ve lo que importa. También por la noche.',image:'ajax-turret.jpg',intro:'Videovigilancia para entradas, patios, negocios y espacios privados. Elegimos el encuadre, la luz y la grabación con el mismo cuidado que la cámara. Consulta las imágenes desde el móvil con la conectividad adecuada.',blocks:[
 ['Una cámara para cada punto.','Una vista general del patio no pide lo mismo que una imagen útil de una entrada. Antes de instalar revisamos óptica, contraluces, obstáculos, alimentación y conexión de cada cámara.'],
 ['Visión nocturna según tu espacio.','Hay soluciones con infrarrojos y opciones de imagen nocturna en color. El color requiere las condiciones de iluminación del modelo o luz auxiliar. Comprobamos reflejos, alcance y luz disponible; no todas las cámaras ven igual en la oscuridad.'],
 ['Grabación local. Consulta desde el móvil.','Dimensionamos el grabador o almacenamiento compatible según el uso. La duración de las grabaciones depende de la capacidad, calidad y modo de grabación. Una suscripción de nube, cuando se contrata, se presupuesta aparte.'],
 ['Privacidad desde el diseño.','Orientamos la cámara hacia el espacio necesario y configuramos permisos y máscaras de privacidad cuando corresponda. En negocios y comunidades deben revisarse las obligaciones aplicables, la información a las personas y los accesos a las grabaciones.']]},
 {slug:'alarmas-y-camaras',name:'Todo integrado',title:'Instalación de alarmas y cámaras integradas',headline:'Dos sistemas. Mejor conectados.',image:'ajax-kit.jpg',intro:'La alarma detecta. Las cámaras ayudan a comprobar qué ocurre. Diseñamos ambos sistemas como un mismo proyecto, con funciones e integración verificadas para los modelos elegidos.',blocks:[
 ['Recibe el aviso. Comprueba lo que ocurre.','Definimos qué eventos puedes consultar, desde qué aplicación y quién tendrá acceso. La combinación de detección e imágenes permite entender mejor una incidencia.'],
 ['Compatibilidad antes que promesas.','Ajax cuenta con vídeo propio y opciones de integración con determinados equipos de terceros. No todas las cámaras, grabadores y funciones se gestionan desde una sola aplicación. Comprobamos la referencia exacta antes de anunciar una integración.'],
 ['El control, en las manos adecuadas.','Configuramos usuarios y permisos, y te explicamos el manejo del sistema. Al pedir presupuesto no envíes claves, códigos de desarmado ni horarios en que el inmueble está vacío.'],
 ['Preparado para una ampliación.','Estudiamos el crecimiento por fases dentro de la capacidad y compatibilidad del sistema. Si tienes cámaras o alarma, revisamos qué se puede conservar antes de proponer nuevos equipos.']]},
 {slug:'mantenimiento',name:'Mantenimiento',title:'Revisión y mantenimiento de alarmas y cámaras',headline:'Que tu instalación siga cuidando de ti.',image:'ajax-turret.jpg',intro:'Revisión de sistemas existentes, problemas de conexión, baterías y grabación. Antes de cambiarlo todo, comprobamos qué funciona y qué necesita mejorar.',blocks:[
 ['Alarmas y detectores.','Comprobamos alimentación, baterías, comunicaciones y detección. Las pruebas se coordinan con el propietario para evitar avisos innecesarios y verificar el funcionamiento real.'],
 ['Cámaras y grabadores.','Revisamos imagen, visión nocturna, conexiones y almacenamiento. Ver una cámara en directo no confirma que esté grabando correctamente.'],
 ['Ampliar con criterio.','Estudiamos nuevos accesos, puntos de vigilancia y cambios de usuarios. La compatibilidad se determina con los modelos y la configuración existentes.'],
 ['Un alcance claro.','El mantenimiento no está incluido por defecto en una instalación sin cuotas. La revisión, los recambios y las actuaciones acordadas se describen en su presupuesto.']]}
];
export const brands=[
 ['ajax','Ajax','Intrusión y vídeo','Alarmas inalámbricas, detectores y un ecosistema de videovigilancia. Nuestra propuesta protagonista para la protección de intrusión y para estudiar una gestión conjunta de los equipos compatibles.','https://ajax.systems/es/'],
 ['hikvision','Hikvision','Cámaras y grabación','Soluciones de CCTV para viviendas y negocios. Elegimos el modelo según encuadre, iluminación, almacenamiento y funciones de detección; no todas las gamas tienen las mismas prestaciones.','https://www.hikvision.com/es/'],
 ['dahua','Dahua','Videovigilancia','Cámaras y grabadores para diseñar una instalación a medida. El presupuesto identifica los equipos, la grabación y las funciones nocturnas del modelo seleccionado.','https://www.dahuasecurity.com/es/'],
 ['uniview','Uniview','Vídeo IP','Sistemas de cámaras IP y grabación. Revisamos red, alimentación y almacenamiento para que el proyecto no dependa solo del número de megapíxeles.','https://www.uniview.com/'],
 ['nivian','Nivian','Seguridad conectada','Opciones para necesidades domésticas y pequeños negocios. Comprobamos la cobertura y la conectividad disponible antes de elegir una solución para el inmueble.','https://www.nivianhome.com/'],
 ['ezviz','EZVIZ','Vídeo para el hogar','Cámaras orientadas al entorno doméstico y al uso desde su aplicación. Explicamos almacenamiento local, acceso remoto y costes de servicios opcionales del modelo elegido.','https://www.ezviz.com/es']
].map(([slug,name,tag,text,url])=>({slug,name,tag,text,url}));
export const faq=[
 ['¿De verdad no hay cuotas mensuales?','La solución base es autogestionada y no lleva cuota mensual obligatoria por central receptora. Equipos, instalación y extras se detallan: conectividad móvil, mantenimiento o nube opcionales pueden tener costes propios.'],
 ['¿La alarma inalámbrica depende del Wi-Fi?','No para comunicar los detectores con la central: los dispositivos Ajax compatibles utilizan radio. Para recibir avisos en el móvil se configura la conexión de la central según el equipo y la cobertura disponible.'],
 ['¿Qué significa alarma de grado 2?','Es una clasificación técnica de seguridad. Debe corresponder a los equipos y al diseño de la instalación; no implica invulnerabilidad ni que cualquier combinación de productos cumpla ese grado.'],
 ['¿Todas las cámaras ven en color por la noche?','No. Algunas utilizan infrarrojos; otras ofrecen color cuando hay suficiente luz o con iluminación auxiliar. La elección depende del modelo y de las condiciones de cada punto.'],
 ['¿Puedo gestionar alarma y cámaras juntas?','Sí, en configuraciones compatibles. Comprobamos central, cámaras, grabador y funciones disponibles. No se anuncia integración universal entre todas las marcas.'],
 ['¿Instaláis en mi pueblo?','Consulta el directorio de provincias y municipios. La disponibilidad, visita y condiciones se confirman al preparar el presupuesto. No se anuncian oficinas ni tiempos de llegada fijos en cada municipio.']
];
