import {e} from './lib.mjs';

// Guías editoriales compartidas: no se disfrazan como experiencia local ni testimonios.
export const guides=[
 {slug:'alarmas-sin-cuotas',title:'Alarmas sin cuotas: qué incluye y qué debes revisar',description:'Qué pagas al instalar una alarma sin cuotas, qué gastos pueden ser opcionales y cómo elegir conectividad, grado 2 y avisos al móvil.',label:'Alarmas sin cuotas',category:'ALARMAS',service:'/alarmas/',intro:'Sin cuotas mensuales obligatorias no significa sin instalación, sin mantenimiento o sin ninguna conexión. Lo importante es saber qué compras, quién recibe los avisos y qué gastos pueden aparecer después.',blocks:[
 ['Qué significa autogestionar tu alarma','En la propuesta base, eres tú quien recibe y gestiona los avisos con las personas autorizadas. No se incluye una central receptora que revise eventos o coordine una respuesta. El presupuesto debe distinguir el suministro de los equipos, su montaje, la puesta en marcha y cualquier servicio contratado aparte. No es lo mismo comprar una alarma que contratar vigilancia.'],
 ['Qué debe incluir el presupuesto inicial','Pide que se identifiquen la central, los detectores, las sirenas y los controles, con su referencia y cantidad. También conviene concretar ubicación, montaje, configuración de usuarios y pruebas. Una propuesta comparable indica desplazamiento, impuestos y exclusiones, en lugar de mostrar solo el precio de un kit. Las funciones de la app y el almacenamiento se comprueban con los modelos elegidos.'],
 ['Qué puede tener un coste posterior','Una tarjeta SIM y su tarifa de datos, un servicio de almacenamiento en la nube o un mantenimiento contratado pueden generar pagos periódicos. El cambio de pilas, una ampliación o una reparación son conceptos distintos de la cuota de vigilancia. Se deben explicar antes de aceptar el trabajo. No publicamos una tarifa universal porque una vivienda con dos accesos y un local con varios espacios requieren proyectos diferentes.'],
 ['Sin cables, con comunicación protegida','Los dispositivos Jeweller compatibles se enlazan por radio con la central mediante comunicación cifrada y supervisada. Esa conexión permite evitar el cableado entre sensores y central; no elimina la necesidad de alimentar el hub. Para avisar a distancia también se necesita una vía exterior operativa. Se prueba la señal en las ubicaciones reales, no solo cerca de la central.'],
 ['Grado 2 y uso cotidiano','La certificación anunciada tiene que corresponder a los equipos y al diseño de la instalación; no se deduce únicamente de la marca. Conviene dejar configuradas las personas autorizadas, comprobar la recepción de avisos y explicar el armado y desarmado. Para dormir en casa se puede estudiar el Modo Noche con los detectores seleccionados. Ningún sistema debe venderse como invulnerable.']
 ],sources:[['Protocolo Jeweller','https://ajax.systems/es/support/posts/jeweller-radio-protocol/'],['Grados de seguridad','https://ajax.systems/es/blog/what-is-a-security-grade/'],['Modo Noche','https://ajax.systems/es/support/posts/what-is-night-mode/']]},
 {slug:'vision-nocturna-y-grabacion',title:'Cámaras: visión nocturna, directo y grabación',description:'Diferencias entre infrarrojos y color nocturno, ver en directo y guardar grabaciones. Qué revisar al elegir cámaras de seguridad.',label:'Visión nocturna y grabación',category:'CÁMARAS',service:'/camaras/',intro:'Una cámara debe ofrecer una imagen útil en el punto que quieres proteger. La resolución importa, pero también la luz, la distancia, el encuadre, la alimentación y dónde se conserva el vídeo.',blocks:[
 ['Infrarrojos y color nocturno','Una cámara con infrarrojos puede iluminar la escena con luz infrarroja y mostrar imagen nocturna habitualmente en blanco y negro. Para imagen en color hay que valorar la sensibilidad del equipo, la luz ambiente y, cuando corresponda, la iluminación visible auxiliar. Por ejemplo, Ajax distingue TurretCam y TurretCam HL, con iluminación híbrida. No atribuimos color en oscuridad total a cualquier cámara.'],
 ['La prueba que realmente importa','Antes de dar por bueno el encuadre, conviene probar un recorrido real a la distancia de interés y con la iluminación nocturna de ese acceso. Una imagen general agradable no garantiza apreciar el detalle necesario. Hay que revisar reflejos de paredes cercanas, contraluces y elementos que invadan el campo de visión. No hace falta grabar toda la fachada si el objetivo es comprobar quién pasa por una puerta.'],
 ['Ver ahora y revisar después','La vista en directo muestra el momento actual. El archivo exige almacenamiento compatible y configurado: grabador, tarjeta cuando el modelo la admite o servicio de nube contratado. La capacidad y el tiempo que puede conservarse dependen del número de cámaras, calidad, compresión y modo de grabación. El presupuesto debe concretar el almacenamiento, y la entrega debe incluir una prueba de reproducción.'],
 ['PoE y cámaras inalámbricas','PoE permite transportar datos y alimentación por un cable de red compatible. Una cámara conectada por Wi-Fi no necesariamente funciona con batería: puede necesitar una toma eléctrica. Las cámaras IP cableadas se eligen por su adecuación al proyecto, no se anuncian como equipos sin cables. Además, la batería del hub de alarma no respalda por sí sola ni cámaras ni grabador.'],
 ['Permisos y privacidad del vídeo','Define quién puede ver el directo, acceder a grabaciones o cambiar ajustes. El encuadre, los avisos y la conservación de imágenes deben adaptarse al uso y a las obligaciones aplicables; instalar una cámara no autoriza a captar indiscriminadamente espacios ajenos. La AEPD ofrece criterios específicos para viviendas, negocios y comunidades. El servicio de instalación debe valorar esas necesidades antes de fijar posiciones.']
 ],sources:[['Manual TurretCam','https://ajax.systems/es/support/manuals/turretcam/'],['TurretCam HL','https://ajax.systems/es/products/turretcam-hl/'],['Grabador NVR','https://ajax.systems/es/support/manuals/nvr/'],['Videovigilancia y privacidad','https://www.aepd.es/areas-de-actuacion/videovigilancia']]},
 {slug:'seguridad-segunda-residencia',title:'Alarmas y cámaras para una segunda residencia',description:'Cómo planificar accesos, comunicaciones, cámaras, usuarios y detección adicional en una casa de pueblo o segunda residencia.',label:'Segundas residencias',category:'VIVIENDAS',service:'/alarmas-y-camaras/',intro:'En una casa que utilizas por temporadas importa tanto detectar un evento como saber si el sistema sigue conectado. El proyecto debe partir de los accesos, la alimentación y las personas que recibirán los avisos.',blocks:[
 ['Puertas, ventanas y recorridos','Un contacto de apertura y un detector de movimiento cumplen funciones distintas. Se estudian puertas, ventanas accesibles y zonas de paso, en lugar de repartir sensores al azar. Los detectores de cortina permiten plantear áreas de detección estrechas con equipos adecuados a interior o exterior. Las sirenas y los controles se eligen también según el inmueble y la forma de utilizarlo.'],
 ['Cobertura real antes de elegir el hub','No basta con que haya cobertura móvil en el pueblo: hay que probarla en el punto donde se instalará la central. También se comprueba el enlace por radio de cada detector, especialmente cuando existen muros, plantas o anexos. Una vía móvil configurada puede complementar la conexión fija. Sin ninguna comunicación exterior disponible no debe contarse con control remoto ni avisos a distancia.'],
 ['Qué ocurre durante un apagón','La autonomía de respaldo depende del modelo y del estado y configuración de su batería. El hub no alimenta automáticamente el router, las cámaras o el grabador. Para estos equipos se valora un respaldo propio cuando el proyecto lo necesita. Conviene revisar qué deja de funcionar en cada escenario antes de decidir la solución, no descubrirlo cuando la vivienda está vacía.'],
 ['Comprobar un aviso y revisar un acceso','MotionCam ofrece fotos asociadas a eventos de alarma con los dispositivos y configuración compatibles; no es una cámara para grabación continua. Para ver una entrada o consultar una secuencia anterior se necesita videovigilancia y almacenamiento. La integración entre alarma y vídeo se verifica por modelo, evitando prometer que cualquier cámara de cualquier marca funciona igual.'],
 ['Humo, agua y personas autorizadas','Pueden valorarse detectores compatibles de humo y de fugas como protección adicional, con el modelo y ubicación apropiados. No sustituyen las medidas de prevención ni las revisiones que correspondan. Define también quién recibe avisos y qué permisos necesita cada persona. Al solicitar presupuesto basta con describir el inmueble: no envíes códigos de desarmado, contraseñas ni fechas de ausencia.']
 ],sources:[['Hub 2 y comunicaciones','https://ajax.systems/es/support/manuals/hub-2/'],['MotionCam','https://ajax.systems/es/support/manuals/motioncam/'],['Gama de dispositivos Ajax','https://ajax.systems/es/products/']]},
 {slug:'presupuesto-instalacion',title:'Qué debe incluir un presupuesto de alarmas y cámaras',description:'Compara presupuestos de alarmas y cámaras: equipos, instalación, desplazamiento, grabación, configuración, impuestos y posibles extras.',label:'Comparar presupuestos',category:'INSTALACIÓN',service:'/contacto/',intro:'Dos presupuestos con el mismo número de cámaras o detectores no siempre incluyen el mismo trabajo. Esta lista te ayuda a comparar lo que se instalará y lo que podrás hacer con el sistema.',blocks:[
 ['Alcance antes que precio de un kit','Describe el tipo de inmueble, accesos y zonas que necesitas proteger. Indica si ya tienes alarma, cámaras, cableado o Internet. Con esa información se puede preparar una primera valoración y acordar si hace falta una visita. Un importe cerrado sin conocer alimentación, recorridos de cable o cobertura puede dejar fuera trabajos necesarios.'],
 ['Equipos identificados por referencia','La propuesta debe permitir reconocer central, detectores, sirenas, controles, cámaras y grabador, cuando los incluya. Marca, referencia, cantidad y prestaciones relevantes permiten comprobar si las ofertas son comparables. En vídeo interesa saber el tipo de lente, la solución nocturna y el almacenamiento; en intrusión, qué se detecta y cómo se transmite el aviso.'],
 ['Montaje, configuración y entrega','Aclara quién aporta alimentación, cableado, soportes y otros materiales, y qué remates quedan incluidos. Conviene definir las pruebas: detección, avisos, imagen nocturna, reproducción y permisos. Pide también que se identifique cómo solicitar asistencia después de la entrega. La explicación de uso y el acceso del propietario a sus cuentas deben formar parte de la entrega acordada. No compartas contraseñas o códigos de alarma en una consulta inicial.'],
 ['Cuotas, mantenimiento y ampliaciones','Diferencia los gastos iniciales de la conectividad, servicios opcionales, nube o mantenimiento que se contraten. Solicita condiciones de futuras intervenciones y sustituciones. Una alarma autogestionada no equivale a vigilancia por una central receptora. El servicio de instalación no debe presentarse como garantía de respuesta policial, ni debe anunciar recambios gratuitos si no están incluidos.'],
 ['Antes de aceptar','Revisa el total, los impuestos, el desplazamiento, el alcance de los trabajos y cualquier exclusión. Elige la solución que cubre tus necesidades, no necesariamente la que contiene más aparatos. Para pedir una valoración a Rapid, indica municipio y provincia, tipo de inmueble y si buscas alarma, cámaras o ambas. No mostramos precios de ejemplo como si fueran tarifas reales de la empresa.']
 ],sources:[]}
];
export const guideUrl=g=>`/guias/${g.slug}/`;
export function guideCards(items=guides,compact=false){return `<div class="guide-grid${compact?' guide-compact':''}">${items.map(g=>`<article class="guide-card"><span class="eyebrow guide-kicker">${e(g.category)}</span><h3>${e(g.label)}</h3><p>${e(g.description)}</p><a class="text-link" href="${guideUrl(g)}">Leer la guía <span aria-hidden="true">→</span></a></article>`).join('')}</div>`;}
export function guideSection(compact=false){return `<section class="section wrap guide-section" aria-labelledby="guides-title"><div class="section-heading"><div><p class="eyebrow">ANTES DE INSTALAR</p><h2 id="guides-title">Decide con información.<br><span class="muted">Protege con criterio.</span></h2></div><p>Respuestas para comparar soluciones y preparar tu instalación, sin tecnicismos innecesarios.</p></div>${guideCards(compact?guides.slice(0,2):guides,compact)}<p class="guide-related"><a class="text-link" href="/guias/">Todas las guías de seguridad <span aria-hidden="true">→</span></a></p></section>`;}
export function guidesPage(){return `<section class="simple-hero wrap"><p class="eyebrow">GUÍAS PRÁCTICAS</p><h1>Elegir bien también<br>es proteger.</h1><p class="lead">Qué necesitas saber sobre alarmas, cámaras y presupuestos antes de decidir tu instalación.</p></section><section class="wrap section">${guideCards()}</section>`;}
export function guidePage(g){return `<section class="simple-hero wrap"><p class="eyebrow">GUÍA / ${e(g.category)}</p><h1>${e(g.title)}</h1><p class="lead">${e(g.intro)}</p></section><article class="wrap guide-article">${g.blocks.map(([title,text],i)=>`<section id="paso-${i+1}"><h2>${e(title)}</h2><p>${e(text)}</p></section>`).join('')}${g.sources.length?`<aside class="guide-sources"><strong>Fuentes técnicas y ampliación:</strong> ${g.sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${e(title)}</a>`).join(' · ')}. Guía editorial de Rapid; prestaciones según los equipos elegidos.</aside>`:''}<div class="guide-actions"><a class="button" href="/contacto/">Consultar mi instalación <span aria-hidden="true">→</span></a><a class="text-link" href="${g.service==='/contacto/'?'/zonas/':g.service}">${g.service==='/contacto/'?'Buscar mi pueblo':'Ver la solución'}</a><a class="text-link" href="/guias/">Otras guías</a></div></article>`;}
