import {e} from './lib.mjs';

// Guías editoriales compartidas: no se disfrazan como experiencia local ni testimonios.
export const guides=[
 {slug:'alarmas-sin-cuotas',title:'Alarmas sin cuotas: qué incluye y qué debes revisar',description:'Qué pagas al instalar una alarma sin cuotas, qué gastos pueden ser opcionales y cómo elegir conectividad, grado 2 y avisos al móvil.',label:'Alarmas sin cuotas',category:'ALARMAS',service:'/alarmas/',intro:'Sin cuotas mensuales obligatorias no significa sin instalación, sin mantenimiento o sin ninguna conexión. Lo importante es saber qué compras, quién recibe los avisos y qué gastos pueden aparecer después.',blocks:[
 ['Qué significa autogestionar tu alarma','En la propuesta base, eres tú quien recibe y gestiona los avisos con las personas autorizadas. No se incluye una central receptora que revise eventos o coordine una respuesta. El presupuesto debe distinguir el suministro de los equipos, su montaje, la puesta en marcha y cualquier servicio contratado aparte. No es lo mismo comprar una alarma que contratar vigilancia.'],
 ['Qué debe incluir el presupuesto inicial','Pide que se identifiquen la central, los detectores, las sirenas y los controles, con su referencia y cantidad. También conviene concretar ubicación, montaje, configuración de usuarios y pruebas. Una propuesta comparable indica desplazamiento, impuestos y exclusiones, en lugar de mostrar solo el precio de un kit. Las funciones de la app y el almacenamiento se comprueban con los modelos elegidos.'],
 ['Qué puede tener un coste posterior','Una tarjeta SIM y su tarifa de datos, un servicio de almacenamiento en la nube o un mantenimiento contratado pueden generar pagos periódicos. El cambio de pilas, una ampliación o una reparación son conceptos distintos de la cuota de vigilancia. Se deben explicar antes de aceptar el trabajo. No publicamos una tarifa universal porque una vivienda con dos accesos y un local con varios espacios requieren proyectos diferentes.'],
 ['Sin cables, con comunicación protegida','Los dispositivos Jeweller compatibles se enlazan por radio con la central mediante comunicación cifrada y supervisada. Esa conexión permite evitar el cableado entre sensores y central; no elimina la necesidad de alimentar el hub. Para avisar a distancia también se necesita una vía exterior operativa. Se prueba la señal en las ubicaciones reales, no solo cerca de la central.'],
 ['Grado 2 y uso cotidiano','La certificación anunciada tiene que corresponder a los equipos y al diseño de la instalación; no se deduce únicamente de la marca. Conviene dejar configuradas las personas autorizadas, comprobar la recepción de avisos y explicar el armado y desarmado. Para dormir en casa se puede estudiar el Modo Noche con los detectores seleccionados. Ningún sistema debe venderse como invulnerable.']
 ],sources:[['Protocolo Jeweller','https://ajax.systems/es/support/posts/jeweller-radio-protocol/'],['Grados de seguridad','https://ajax.systems/es/blog/what-is-a-security-grade/'],['Modo Noche','https://ajax.systems/es/support/posts/what-is-night-mode/']]},
 {slug:'vision-nocturna-y-grabacion',title:'Cámaras: visión nocturna, directo y grabación',description:'Diferencias entre infrarrojos y color nocturno, ver en directo y guardar grabaciones. Qué revisar al elegir cámaras de seguridad.',label:'Visión nocturna y grabación',category:'CÁMARAS',service:'/camaras/',intro:'Una cámara debe ofrecer una imagen útil en el punto que quieres proteger. La resolución importa, pero también la luz, la distancia, el encuadre, la alimentación y dónde se conserva el vídeo.',blocks:[
 ['Infrarrojos y color nocturno','Una cámara con infrarrojos puede iluminar la escena con luz infrarroja y mostrar imagen nocturna habitualmente en blanco y negro. Para imagen en color hay que valorar la sensibilidad del equipo, la luz ambiente y, cuando corresponda, la iluminación visible auxiliar. Por ejemplo, Ajax distingue TurretCam y TurretCam HL, con iluminación híbrida. No atribuimos color en oscuridad total a cualquier cámara.'],
 ['La prueba que realmente importa','Antes de dar por bueno el encuadre, conviene probar un recorrido real a la distancia de interés y con la iluminación nocturna de ese acceso. Una imagen general agradable no garantiza apreciar el detalle necesario. Hay que revisar reflejos de paredes cercanas, contraluces y elementos que invadan el campo de visión. No hace falta grabar toda la fachada si el objetivo es comprobar quién pasa por una puerta.'],
 ['Ver ahora y revisar después','La vista en directo muestra el momento actual. El archivo exige almacenamiento compatible y configurado: grabador, tarjeta cuando el modelo la admite o servicio de nube contratado. La capacidad y el tiempo que puede conservarse dependen del número de cámaras, calidad, compresión y modo de grabación. El presupuesto debe concretar el almacenamiento, y la entrega debe incluir una prueba de reproducción.'],
 ['PoE y cámaras inalámbricas','PoE permite transportar datos y alimentación por un cable de red compatible. Una cámara conectada por Wi-Fi no necesariamente funciona con batería: puede necesitar una toma eléctrica. Las cámaras IP cableadas se eligen por su adecuación al proyecto, no se anuncian como equipos sin cables. Además, la batería del hub de alarma no respalda por sí sola ni cámaras ni grabador.'],
 ['Permisos y privacidad del vídeo','Define quién puede ver el directo, acceder a grabaciones o cambiar ajustes. El encuadre, los avisos y la conservación de imágenes deben adaptarse al uso y a las obligaciones aplicables; instalar una cámara no autoriza a captar indiscriminadamente espacios ajenos. La AEPD ofrece criterios específicos para viviendas, negocios y comunidades. El servicio de instalación debe valorar esas necesidades antes de fijar posiciones.']
 ],sources:[['Manual TurretCam','https://ajax.systems/es/support/manuals/turretcam/'],['TurretCam HL','https://ajax.systems/es/products/turretcam-hl/'],['Grabador NVR','https://ajax.systems/es/support/manuals/nvr/'],['Videovigilancia y privacidad','https://www.aepd.es/areas-de-actuacion/videovigilancia']]},
 {slug:'seguridad-segunda-residencia',title:'Alarmas y cámaras para una segunda residencia',description:'Cómo planificar accesos, comunicaciones, cámaras, usuarios y detección adicional en una casa de pueblo o segunda residencia.',label:'Segundas residencias',category:'VIVIENDAS',service:'/alarmas-y-camaras/',intro:'En una casa que utilizas por temporadas importa tanto detectar un evento como saber si el sistema sigue conectado. El proyecto debe partir de los accesos, la alimentación y las personas que recibirán los avisos.',blocks:[
 ['Puertas, ventanas y recorridos','Un contacto de apertura y un detector de movimiento cumplen funciones distintas. Se estudian puertas, ventanas accesibles y zonas de paso, en lugar de repartir sensores al azar. Los detectores de cortina permiten plantear áreas de detección estrechas con equipos adecuados a interior o exterior. Las sirenas y los controles se eligen también según el inmueble y la forma de utilizarlo.'],
 ['Cobertura real antes de elegir el hub','No basta con que haya cobertura móvil en el pueblo: hay que probarla en el punto donde se instalará la central. También se comprueba el enlace por radio de cada detector, especialmente cuando existen muros, plantas o anexos. Una vía móvil configurada puede complementar la conexión fija. Sin ninguna comunicación exterior disponible no debe contarse con control remoto ni avisos a distancia.'],
 ['Qué ocurre durante un apagón','La autonomía de respaldo depende del modelo y del estado y configuración de su batería. El hub no alimenta automáticamente el router, las cámaras o el grabador. Para estos equipos se valora un respaldo propio cuando el proyecto lo necesita. Conviene revisar qué deja de funcionar en cada escenario antes de decidir la solución, no descubrirlo cuando la vivienda está vacía.'],
 ['Comprobar un aviso y revisar un acceso','MotionCam ofrece fotos asociadas a eventos de alarma con los dispositivos y configuración compatibles; no es una cámara para grabación continua. Para ver una entrada o consultar una secuencia anterior se necesita videovigilancia y almacenamiento. La integración entre alarma y vídeo se verifica por modelo, evitando prometer que cualquier cámara de cualquier marca funciona igual.'],
 ['Humo, agua y personas autorizadas','Pueden valorarse detectores compatibles de humo y de fugas como protección adicional, con el modelo y ubicación apropiados. No sustituyen las medidas de prevención ni las revisiones que correspondan. Define también quién recibe avisos y qué permisos necesita cada persona. Al solicitar presupuesto basta con describir el inmueble: no envíes códigos de desarmado, contraseñas ni fechas de ausencia.']
 ],sources:[['Hub 2 y comunicaciones','https://ajax.systems/es/support/manuals/hub-2/'],['MotionCam','https://ajax.systems/es/support/manuals/motioncam/'],['Gama de dispositivos Ajax','https://ajax.systems/es/products/']]},
 {slug:'presupuesto-instalacion',title:'Qué debe incluir un presupuesto de alarmas y cámaras',description:'Compara presupuestos de alarmas y cámaras: equipos, instalación, desplazamiento, grabación, configuración, impuestos y posibles extras.',label:'Comparar presupuestos',category:'INSTALACIÓN',service:'/contacto/',intro:'Dos presupuestos con el mismo número de cámaras o detectores no siempre incluyen el mismo trabajo. Esta lista te ayuda a comparar lo que se instalará y lo que podrás hacer con el sistema.',blocks:[
 ['Alcance antes que precio de un kit','Describe el tipo de inmueble, accesos y zonas que necesitas proteger. Indica si ya tienes alarma, cámaras, cableado o Internet. Con esa información se puede preparar una primera valoración y acordar si hace falta una visita. Un importe cerrado sin conocer alimentación, recorridos de cable o cobertura puede dejar fuera trabajos necesarios.'],
 ['Equipos identificados por referencia','La propuesta debe permitir reconocer central, detectores, sirenas, controles, cámaras y grabador, cuando los incluya. Marca, referencia, cantidad y prestaciones relevantes permiten comprobar si las ofertas son comparables. En vídeo interesa saber el tipo de lente, la solución nocturna y el almacenamiento; en intrusión, qué se detecta y cómo se transmite el aviso.'],
 ['Montaje, configuración y entrega','Aclara quién aporta alimentación, cableado, soportes y otros materiales, y qué remates quedan incluidos. Conviene definir las pruebas: detección, avisos, imagen nocturna, reproducción y permisos. Pide también que se identifique cómo solicitar asistencia después de la entrega. La explicación de uso y el acceso del propietario a sus cuentas deben formar parte de la entrega acordada. No compartas contraseñas o códigos de alarma en una consulta inicial.'],
 ['Cuotas, mantenimiento y ampliaciones','Diferencia los gastos iniciales de la conectividad, servicios opcionales, nube o mantenimiento que se contraten. Solicita condiciones de futuras intervenciones y sustituciones. Una alarma autogestionada no equivale a vigilancia por una central receptora. El servicio de instalación no debe presentarse como garantía de respuesta policial, ni debe anunciar recambios gratuitos si no están incluidos.'],
 ['Antes de aceptar','Revisa el total, los impuestos, el desplazamiento, el alcance de los trabajos y cualquier exclusión. Elige la solución que cubre tus necesidades, no necesariamente la que contiene más aparatos. Para pedir una valoración a Rapid, indica municipio y provincia, tipo de inmueble y si buscas alarma, cámaras o ambas. No mostramos precios de ejemplo como si fueran tarifas reales de la empresa.']
 ],sources:[]},
 {slug:'camaras-exteriores-noche',title:'Cámaras exteriores: visión nocturna, luz y ubicación',description:'Cómo elegir cámaras exteriores: infrarrojos, color nocturno, contraluces, altura, alcance y ubicación para obtener imágenes útiles de accesos y perímetros.',label:'Cámaras exteriores y noche',category:'CÁMARAS',service:'/camaras/',intro:'Una cámara exterior funciona bien cuando el punto de instalación, la luz y el objetivo de vigilancia están definidos antes de elegir el modelo. No basta con colocar una cámara de muchos megapíxeles en cualquier esquina.',blocks:[
 ['Empieza por lo que quieres reconocer','Antes de hablar de resolución, define qué necesitas ver: una puerta, una entrada de vehículos, un patio o un perímetro. La distancia al punto de interés condiciona la óptica y el encuadre. Una cámara demasiado abierta puede mostrar mucho espacio y poco detalle; una demasiado cerrada puede perder zonas de paso. En una visita se revisan recorridos, alturas, obstáculos y el lugar desde el que realmente se producirá el acceso.'],
 ['Infrarrojos, luz blanca y color nocturno','Los infrarrojos permiten iluminar de noche sin luz visible y suelen producir imagen monocroma. Las gamas de baja iluminación o con luz blanca pueden ofrecer color cuando el modelo y la escena lo permiten. Esa prestación depende de la sensibilidad, la óptica y la luz disponible. Conviene probar el acceso de noche: paredes cercanas, canalones, vegetación o matrículas reflectantes pueden alterar el resultado mucho más que una cifra de catálogo.'],
 ['Contraluces y puntos difíciles','Puertas con luz interior intensa, escaparates, faros de vehículos o zonas parcialmente iluminadas pueden crear diferencias fuertes de exposición. En esos puntos se valora el rango dinámico y, sobre todo, el encuadre. A veces mover la cámara unos centímetros mejora más la imagen que cambiar de resolución. También se evita instalar donde una rama, un alero o una pared ocupen demasiado campo de visión y provoquen reflejos nocturnos.'],
 ['Exterior significa montaje, alimentación y red','Una cámara apta para exterior necesita una ubicación compatible con su protección ambiental, fijación firme y una entrada de cable bien resuelta. En instalaciones IP puede utilizarse PoE para datos y alimentación con cable de red compatible. En otros casos se requiere alimentación local. La cobertura Wi-Fi no debe suponerse desde dentro de la vivienda; se comprueba en el punto real. Para ubicaciones aisladas se estudian alternativas 4G o solares por separado.'],
 ['Privacidad y mantenimiento','El encuadre debe limitarse a la zona necesaria. Captar de forma indiscriminada espacios ajenos no es un objetivo de una instalación bien diseñada. También hay que pensar en el mantenimiento: una lente expuesta a suciedad, lluvia, insectos o vegetación necesita acceso razonable para revisión. Al entregar la instalación conviene probar directo, grabación y visión nocturna, y dejar claro quién puede consultar imágenes o cambiar ajustes.']
 ],sources:[['Uniview ColorHunter para exterior','https://global.uniview.com/es/Products/Network_Cameras/Owlview_Series/Owlview/IPC3624LE-ADF28K-WP/'],['Hikvision ColorVu','https://content.hikvision.com/es/tecnologia/colorvu2020'],['Videovigilancia y privacidad','https://www.aepd.es/areas-de-actuacion/videovigilancia']]},
 {slug:'grabacion-nvr-almacenamiento',title:'Grabación de cámaras: NVR, tarjeta o nube',description:'Qué cambia entre grabar en NVR, tarjeta microSD o nube. Capacidad, reproducción, red y costes que conviene definir antes de instalar cámaras.',label:'NVR y almacenamiento',category:'CÁMARAS',service:'/camaras/',intro:'Ver una cámara en directo no demuestra que exista una grabación útil. El almacenamiento debe diseñarse junto con las cámaras: dónde se guarda, cuánto tiempo, quién puede reproducirlo y qué ocurre si falla la red.',blocks:[
 ['NVR: grabación centralizada','Un grabador de red recibe los flujos de cámaras IP compatibles y concentra almacenamiento, reproducción y gestión. Es una opción habitual cuando hay varias cámaras o se necesita revisar eventos desde un único punto. Hay que dimensionar canales, discos, ancho de banda y compatibilidad. No todo NVR admite todas las funciones inteligentes de cualquier cámara, aunque exista vídeo básico mediante protocolos compatibles. La referencia exacta debe quedar identificada en el presupuesto.'],
 ['Tarjeta en la propia cámara','Algunos modelos aceptan tarjeta microSD y pueden guardar vídeo de forma local. Es útil en instalaciones pequeñas o como almacenamiento complementario, pero capacidad, ciclos de escritura y funciones dependen del equipo. Si la cámara desaparece o se avería, ese soporte puede dejar de estar disponible. Por eso conviene decidir si la grabación local cumple el objetivo o si se necesita además un grabador en otra ubicación.'],
 ['Nube y servicios opcionales','La nube puede aportar acceso o almacenamiento remoto en determinados ecosistemas, normalmente con condiciones y, en algunos casos, cuotas propias. No debe confundirse con la instalación básica ni darse por incluida si no aparece en el presupuesto. También hay que revisar qué resolución, duración o eventos conserva el servicio. Una solución autogestionada puede no tener cuota de central receptora y, aun así, contratar servicios digitales opcionales.'],
 ['Cuánto tiempo cabe realmente','No existe un número universal de días de grabación. El resultado depende del número de cámaras, resolución, imágenes por segundo, compresión, actividad de la escena y si se graba continuamente o por eventos. La capacidad se calcula con un margen razonable y luego se comprueba en la instalación. Si conservar cierto periodo es importante, debe figurar como objetivo de diseño y no como promesa genérica basada solo en el tamaño del disco.'],
 ['La prueba de entrega','Antes de dar por terminada una instalación hay que abrir el directo, buscar una grabación anterior, reproducirla y comprobar la fecha y hora. También se revisan usuarios, permisos y acceso remoto. Si el grabador depende de un switch, router o alimentación concreta, se explica qué equipos forman parte de la cadena. Un sistema útil es aquel que el propietario sabe consultar cuando realmente lo necesita.']
 ],sources:[['Ajax NVR','https://ajax.systems/es/support/manuals/nvr/'],['Videovigilancia y privacidad','https://www.aepd.es/areas-de-actuacion/videovigilancia']]},
 {slug:'camaras-4g-solares',title:'Cámaras 4G y solares: cuándo tienen sentido',description:'Cuándo valorar una cámara 4G o solar en fincas, segundas residencias y ubicaciones sin fibra. Cobertura, energía, datos y límites a comprobar.',label:'Cámaras 4G y solares',category:'CÁMARAS',service:'/camaras/',intro:'Una cámara 4G o solar puede resolver ubicaciones donde no llega la red fija o no existe una toma cercana, pero no convierte cualquier punto en una instalación autónoma. Cobertura, consumo, batería y orientación se comprueban antes de elegirla.',blocks:[
 ['Primero: cobertura móvil real','Que un municipio tenga cobertura no significa que la cámara vaya a tenerla en la fachada, finca o almacén donde se instalará. La señal se comprueba en el punto y con el operador que vaya a utilizar la SIM. Muros, desniveles y vegetación pueden cambiar el resultado. También se revisa el consumo de datos previsto, porque directo frecuente, mayor calidad o más eventos pueden incrementar la transferencia respecto a un uso ocasional.'],
 ['Solar no significa energía ilimitada','Un panel solar ayuda a recargar la batería, pero su rendimiento depende de orientación, sombras, estación del año y consumo del equipo. Antes de montar se valora si el lugar recibe luz suficiente y si existen árboles, aleros u otros obstáculos. Periodos prolongados de baja producción pueden reducir autonomía. La instalación debe permitir revisar panel, conexiones y batería sin desmontar media fachada o acceder a una zona insegura.'],
 ['No sustituye siempre a un sistema cableado','Cuando hay alimentación y red disponibles, una cámara PoE con grabador puede ofrecer una arquitectura más predecible para uso intensivo y varias cámaras. 4G y solar son especialmente interesantes cuando llevar cable o energía es complicado, pero hay que comparar el objetivo real. Una cámara autónoma para verificar una entrada de finca no tiene las mismas necesidades que un sistema continuo de cuatro u ocho cámaras alrededor de una nave.'],
 ['Dónde se guardan las imágenes','Según el modelo, el vídeo puede almacenarse en tarjeta, nube o mediante funciones compatibles con su plataforma. Conviene saber qué ocurre si se pierde temporalmente la cobertura y qué material queda disponible después. También hay que diferenciar alertas, clips y grabación continua. Antes de comprar una tarjeta o contratar un servicio, se comprueban los formatos, capacidades y opciones admitidas por la referencia elegida.'],
 ['Segunda residencia, finca o punto remoto','En una segunda residencia puede combinarse una alarma con comunicaciones propias y videovigilancia según cobertura y alimentación. En una finca o acceso remoto puede tener más sentido una cámara autónoma bien orientada. En ambos casos el proyecto empieza por el punto a proteger, no por la etiqueta solar o 4G. Rapid comprueba ubicación, señal, energía y forma de consulta antes de presupuestar una solución de este tipo.']
 ],sources:[['Nivian cámara solar 4G','https://www.nivianhome.com/es/producto/nv-cam01-solar4g/'],['Guía de segunda residencia','/guias/seguridad-segunda-residencia/']]},
 {slug:'alarma-vivienda-cerrada-sin-luz',title:'Alarma para piso vacío o vivienda cerrada sin luz',description:'Cómo proteger un piso vacío o vivienda cerrada sin suministro eléctrico con alarma, batería de respaldo, batería externa y comunicación móvil.',label:'Alarma sin luz para vivienda cerrada',category:'ALARMAS',service:'/alarmas/',intro:'Un piso vacío, una vivienda cerrada por temporada o un inmueble sin suministro eléctrico puede seguir necesitando detección y avisos. La solución cambia según si hablamos de un corte temporal o de una vivienda que permanecerá sin red eléctrica durante semanas o meses.',blocks:[
 ['Corte de luz temporal: batería interna del hub','Los hubs Ajax compatibles incorporan una batería de respaldo para mantener la central funcionando cuando desaparece la alimentación externa. La autonomía depende del modelo, del estado de la batería y de la configuración. En Hub 2, Ajax indica hasta 14 horas de funcionamiento autónomo; otros modelos pueden variar. Esta batería está pensada para respaldo durante un apagón, no para considerar que cualquier vivienda puede permanecer sin electricidad de forma indefinida.'],
 ['Vivienda cerrada durante mucho tiempo y sin red eléctrica','Si el inmueble va a permanecer sin suministro eléctrico de forma prolongada, se estudia una alimentación alternativa compatible. Ajax dispone del módulo 6V PSU (type A), que permite alimentar determinados hubs desde una batería externa. El fabricante contempla este uso para sitios vacíos o deteriorados y explica que la autonomía depende de la batería, de los canales de comunicación activos, de la cobertura y de la temperatura. La batería y la fuente deben dimensionarse para el caso real.'],
 ['Avisos sin router: comunicación móvil','Un sistema de alarma necesita una vía de comunicación si quieres recibir avisos cuando no estás en la vivienda. Hub 2 dispone de Ethernet y canales móviles mediante SIM según versión. Si el piso está cerrado y el router está apagado o no existe, se puede valorar la comunicación móvil del hub con cobertura suficiente y una SIM configurada. Antes de instalar se comprueba la señal en el punto donde quedará la central; tener cobertura general en el municipio no garantiza una conexión estable dentro del inmueble.'],
 ['Los detectores consumen distinto que cámaras y router','Los detectores inalámbricos compatibles pueden funcionar con sus propias pilas, pero la batería del hub no alimenta automáticamente cámaras, grabador, router o iluminación. Si además quieres videovigilancia en una vivienda sin luz, esos equipos necesitan una solución energética propia. Por eso una alarma autónoma para detectar apertura o movimiento puede ser viable en un escenario donde mantener varias cámaras grabando continuamente no lo sea. Se separan ambos objetivos en el presupuesto.'],
 ['Qué revisar antes de cerrar un piso','Para proteger un piso cerrado conviene definir puerta principal, ventanas o terraza accesibles, zonas de paso, sirena y personas autorizadas para recibir avisos. También se revisan cobertura móvil, temperatura del lugar donde irá la batería, acceso para mantenimiento y tiempo esperado sin suministro. Si vuelve la electricidad de forma habitual, la batería interna puede actuar como respaldo; si no habrá red eléctrica durante largo tiempo, se calcula una alimentación externa compatible y se deja claro qué autonomía se espera.']
 ],sources:[['Ajax Hub 2: batería y alimentación alternativa','https://support.ajax.systems/es/central-units/hub-2/'],['Manual Hub 2 y canales de comunicación','https://support.ajax.systems/es/manuals/hub-2/'],['Cálculo de batería externa con 6V PSU','https://support.ajax.systems/es/hub2-hub2-plus-from-6v-psu/']]}
];
export const guideUrl=g=>`/guias/${g.slug}/`;
export function guideCards(items=guides,compact=false){return `<div class="guide-grid${compact?' guide-compact':''}">${items.map(g=>`<article class="guide-card"><span class="eyebrow guide-kicker">${e(g.category)}</span><h3>${e(g.label)}</h3><p>${e(g.description)}</p><a class="text-link" href="${guideUrl(g)}">Leer la guía <span aria-hidden="true">→</span></a></article>`).join('')}</div>`;}
export function guideSection(compact=false){const selected=compact?[guides[0],guides[7],guides[4]]:guides;return `<section class="section wrap guide-section" aria-labelledby="guides-title"><div class="section-heading"><div><p class="eyebrow">ANTES DE INSTALAR</p><h2 id="guides-title">Decide con información.<br><span class="muted">Protege con criterio.</span></h2></div><p>Respuestas para comparar soluciones y preparar tu instalación, sin tecnicismos innecesarios.</p></div>${guideCards(selected,compact)}<p class="guide-related"><a class="text-link" href="/guias/">Todas las guías de seguridad <span aria-hidden="true">→</span></a></p></section>`;}
export function guidesPage(){return `<section class="simple-hero wrap"><p class="eyebrow">GUÍAS PRÁCTICAS</p><h1>Elegir bien también<br>es proteger.</h1><p class="lead">Qué necesitas saber sobre alarmas, cámaras y presupuestos antes de decidir tu instalación.</p></section><section class="wrap section">${guideCards()}</section>`;}
export function guidePage(g){return `<section class="simple-hero wrap"><p class="eyebrow">GUÍA / ${e(g.category)}</p><h1>${e(g.title)}</h1><p class="lead">${e(g.intro)}</p></section><article class="wrap guide-article">${g.blocks.map(([title,text],i)=>`<section id="paso-${i+1}"><h2>${e(title)}</h2><p>${e(text)}</p></section>`).join('')}${g.sources.length?`<aside class="guide-sources"><strong>Fuentes técnicas y ampliación:</strong> ${g.sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${e(title)}</a>`).join(' · ')}. Guía editorial de Rapid; prestaciones según los equipos elegidos.</aside>`:''}<div class="guide-actions"><a class="button" href="/contacto/">Consultar mi instalación <span aria-hidden="true">→</span></a><a class="text-link" href="${g.service==='/contacto/'?'/zonas/':g.service}">${g.service==='/contacto/'?'Buscar mi pueblo':'Ver la solución'}</a><a class="text-link" href="/guias/">Otras guías</a></div></article>`;}
