import {e} from './lib.mjs';

// Identidad facilitada por el titular. No se completan NIF, domicilio o correo por inferencia.
export const policyDate='2026-10-09';
const titles={'aviso-legal':'Aviso legal',privacidad:'Política de privacidad',cookies:'Política de cookies'};
const external=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
export function privacySummary(site){
 return `<aside class="privacy-summary" aria-label="Información básica de privacidad"><strong>Responsable: ${e(site.legal.holder)}.</strong> Utilizamos tu consulta para responder y preparar el presupuesto que solicitas. El preparador no la guarda en esta web; al continuar, el texto se comunica a WhatsApp para abrir el mensaje. Puedes llamar como alternativa. <a href="/privacidad/">Finalidades, proveedores y derechos</a>.</aside>`;
}
export function legalPage(kind,site){
 if(!titles[kind])throw Error('Política desconocida: '+kind);
 const contact=`<a href="tel:${e(site.tel)}">${e(site.phone)}</a> o <a href="https://wa.me/${e(site.whatsapp)}" rel="noopener noreferrer">WhatsApp</a>`;
 const sections={
  'aviso-legal':[
   ['Titular del sitio',`<strong>${e(site.brand)} es un sitio web propiedad de ${e(site.legal.holder)}.</strong> Puedes contactar a través de ${contact}.`],
   ['Servicios y presupuestos','Esta web informa sobre instalación de alarmas, cámaras de seguridad, integración y mantenimiento. Solicitar información no realiza una compra ni supone aceptar un presupuesto. Equipos, instalación, desplazamiento, impuestos y servicios opcionales se concretan en la propuesta que se facilite.'],
   ['Alcance de la oferta','Las prestaciones, la certificación de grado 2 y la integración dependen de los equipos y de la configuración contratada. La solución autogestionada sin cuota mensual obligatoria no incluye vigilancia por una central receptora ni aviso automático a la Policía. La disponibilidad en cada municipio se confirma antes de concertar el trabajo.'],
   ['Marcas y contenidos','Ajax, Hikvision, Dahua, Uniview, Nivian y EZVIZ pertenecen a sus respectivos titulares. Su aparición identifica los equipos y no implica una acreditación de distribuidor o instalador oficial. Las fotografías de producto no se presentan como instalaciones realizadas por Rapid en un municipio. Los derechos sobre los materiales de terceros corresponden a sus titulares.'],
   ['Uso y enlaces','Utiliza el sitio sin interferir en su funcionamiento ni facilitar datos de otras personas sin autorización. Los enlaces a fabricantes y otros servicios se abren bajo las condiciones del proveedor correspondiente. La información de esta web no sustituye el estudio de la instalación ni limita los derechos que legalmente correspondan al cliente.']
  ],
  privacidad:[
   ['Responsable y contacto',`El titular de esta web es <strong>${e(site.legal.holder)}</strong>, bajo la marca ${e(site.brand)}. Para consultas de privacidad o para solicitar el ejercicio de tus derechos, utiliza ${contact}, indicando que tu petición se refiere a protección de datos.`],
   ['Qué datos se utilizan','Al navegar, el alojamiento puede tratar dirección IP, información del navegador y registros de peticiones para servir y proteger el sitio. El preparador de consultas utiliza el municipio, servicio y tipo de inmueble que introduces. No pide contraseñas, códigos de alarma ni horarios de ausencia. Al contactar también facilitas el teléfono, nombre u otros datos que decidas comunicar.'],
   ['Para qué y con qué base','Las consultas y solicitudes de presupuesto se atienden para adoptar las medidas precontractuales que solicitas; las comunicaciones generales se responden por el interés legítimo en atenderlas. Los datos técnicos permiten prestar y proteger la web, sobre la base del interés legítimo en su funcionamiento y seguridad. No hay perfiles publicitarios ni decisiones automatizadas en este sitio.'],
   ['Preparador y WhatsApp','Los campos del preparador se procesan en el navegador y no se envían a un formulario ni a una base de datos propia de la web. Al pulsar el botón para continuar, el texto se incluye en un enlace a WhatsApp y se comunica a ese servicio para abrir el mensaje; después decides si lo envías al técnico. Puedes contactar por teléfono sin usar el preparador.'],
   ['Proveedores y transferencias',`La web está alojada en Netlify. WhatsApp es un servicio externo que interviene cuando abres su enlace. Estos proveedores pueden tratar datos fuera del Espacio Económico Europeo conforme a sus condiciones y garantías aplicables. Consulta la ${external('https://www.netlify.com/pdf/netlify-dpa.pdf','información de tratamiento de Netlify')} y la ${external('https://www.whatsapp.com/legal/privacy-policy-eea','política de WhatsApp para el EEE')}. La web no incorpora analítica ni publicidad de terceros.`],
   ['Conservación','El preparador no guarda una copia persistente de los campos en el almacenamiento de esta web. Las consultas recibidas se conservan durante el tiempo necesario para atenderlas; si dan lugar a un servicio o a una reclamación, se aplican las obligaciones de conservación que correspondan. Los registros técnicos y los datos tratados por proveedores externos siguen sus condiciones y la configuración del servicio.'],
   ['Tus derechos',`Puedes solicitar acceso, rectificación, supresión, oposición, limitación y portabilidad cuando procedan. Si un tratamiento se basa en consentimiento, puedes retirarlo sin afectar a su licitud anterior. Contacta con ${e(site.legal.holder)} por los medios indicados; solo debe pedirse información adicional de identidad cuando sea necesaria. También puedes reclamar ante la ${external('https://www.aepd.es/','Agencia Española de Protección de Datos')}.`]
  ],
  cookies:[
   ['Navegación sin seguimiento','El código de esta web no instala cookies de analítica o publicidad ni utiliza almacenamiento local para identificar o perfilar visitantes. Los archivos de diseño, fotografías y buscador se sirven desde el propio alojamiento. No se cargan gestores de etiquetas, mapas, vídeos ni paneles sociales de terceros.'],
   ['Buscador y preparador','La búsqueda y los campos de consulta funcionan en el navegador. Los parámetros de una URL pueden recordar el municipio al pasar a contacto, pero no son cookies. No se guarda la consulta en localStorage ni sessionStorage. El historial o autocompletado que gestione tu navegador es independiente de esta web.'],
   ['Servicios externos',`WhatsApp y las páginas de fabricantes solo se abren cuando pulsas sus enlaces. A partir de ese momento se aplican las políticas del servicio visitado. Los registros técnicos que pueda generar el alojamiento no son cookies del navegador. Puedes ampliar la información en nuestra <a href="/privacidad/">política de privacidad</a>.`],
   ['Consentimiento y controles','Con esta configuración no hay cookies opcionales que aceptar o rechazar, por lo que no se muestra un panel de consentimiento. Puedes borrar o bloquear cookies desde los ajustes de tu navegador. Si se incorporan tecnologías no exentas de consentimiento, deberán permanecer desactivadas hasta tu elección, con opciones de aceptación y rechazo y un mecanismo para retirarla.'],
   ['Titular y consultas',`Este sitio es propiedad de <strong>${e(site.legal.holder)}</strong>. Para una consulta sobre cookies o privacidad, contacta por ${contact}.`]
  ]
 };
 return `<section class="simple-hero wrap policy-hero"><p class="eyebrow">INFORMACIÓN DEL SITIO</p><h1>${titles[kind]}</h1><p class="lead">${kind==='cookies'?'Sin publicidad. Sin analítica de terceros.':'Información clara sobre esta web y tu relación con nosotros.'}</p><p class="fine-print">Última revisión: <time datetime="${policyDate}">9 de octubre de 2026</time>.</p><nav class="policy-nav" aria-label="Información legal">${Object.entries(titles).map(([slug,title])=>`<a href="/${slug}/"${slug===kind?' aria-current="page"':''}>${title}</a>`).join('')}</nav></section><section class="wrap legal-copy">${sections[kind].map(([h,p])=>`<article><h2>${h}</h2><p>${p}</p></article>`).join('')}</section>`;
}
